### ISSUE TITLE
Cli throwing error due to problem with dependency xlsx

### ISSUE THREAD

**Issue by simon-p-r** [circabs/xl-json#4]
C:\Program Files\nodejs\node_modules\xl-json\node_modules\xlsx\xlsx.js:9
             if(typeof cptable === 'undefined') cptable = require('./dist/cpexcel');
                                                   ^

     ReferenceError: cptable is not defined
            at C:\Program Files\nodejs\node_modules\xl-json\node_modules\xlsx\xlsx.js:9:45
            at Object.<anonymous> (C:\Program Files\nodejs\node_modules\xl-      json\node_modules\xlsx\xlsx.js:5389:3)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (C:\Program Files\nodejs\node_modules\xl-json\node_modules\j\j.js:4:12)
    at Module._compile (module.js:425:26)

**Comment by simon-p-r** [comment]
Closed by 019a35285f54a58f6997b6271feb539294e22bf5
